'use client';
import {useState} from 'react';
import {useRouter} from 'next/navigation';
import {createClient} from '../../../../lib/supabase/browser';
import {latestDocuments,daysToExpiry,londonToday} from '../../../../lib/contractor-expiry';
type Doc={id:number;document_type:string;file_name:string;expiry_date:string|null;uploaded_at:string};
export default function ContractorRenewal({contractor,documents,email}:{contractor:{id:number;company_name:string;status:string;expiry_pause_reason:string};documents:Doc[];email:string}){
 const router=useRouter();const current=latestDocuments(documents.map(d=>({...d,documentType:d.document_type,uploadedAt:d.uploaded_at})));const [type,setType]=useState(current.find(d=>d.expiry_date&&daysToExpiry(d.expiry_date)<0)?.document_type||current[0]?.document_type||'Public Liability Insurance');const [expiry,setExpiry]=useState(''),[file,setFile]=useState<File|null>(null),[busy,setBusy]=useState(false),[message,setMessage]=useState('');
 async function upload(e:React.FormEvent){e.preventDefault();if(!file||!expiry||busy)return;setBusy(true);setMessage('');const db=createClient();let path='';let uploaded=false;try{if(!['application/pdf','image/jpeg','image/png','image/webp'].includes(file.type)||file.size===0||file.size>10485760)throw new Error('Use a PDF or image up to 10 MB.');if(expiry<londonToday())throw new Error('Choose a current renewal expiry date.');path=`${contractor.id}/${crypto.randomUUID()}-${file.name.replace(/[^a-zA-Z0-9._-]/g,'-')}`;const {error:up}=await db.storage.from('contractor-documents').upload(path,file,{contentType:file.type,upsert:false});if(up)throw new Error('Upload failed. Please try again.');uploaded=true;const {error}=await db.from('contractor_documents').insert({contractor_id:contractor.id,document_type:type,file_name:file.name,storage_path:path,mime_type:file.type,file_size:file.size,expiry_date:expiry,notes:'Replacement submitted for manager review',uploaded_by:email});if(error)throw new Error(error.message);setFile(null);setExpiry('');setMessage('Replacement uploaded. Your contractor status stays suspended until AVIAF reviews and approves the current documents.');router.refresh();}catch(e){setMessage(uploaded?'Your file was uploaded, but its document record could not be saved. Contact AVIAF before uploading it again.':e instanceof Error?e.message:'Upload failed');}finally{setBusy(false);}}
 return <main className="tenant-shell"><div className="tenant-content"><p className="eyebrow">CONTRACTOR DOCUMENT RENEWALS</p><h1>{contractor.company_name}</h1><p>Status: <strong>{contractor.status}</strong></p>{contractor.expiry_pause_reason&&<p role="status">{contractor.expiry_pause_reason}</p>}<section className="panel tenant-card"><h2>Current document dates</h2>{current.map(d=><p key={d.id}><strong>{d.document_type}</strong> · {d.expiry_date?`${d.expiry_date} · ${daysToExpiry(d.expiry_date)<0?'Expired':daysToExpiry(d.expiry_date)+' days remaining'}`:'No expiry date'}</p>)}</section><section className="panel tenant-card"><h2>Upload a replacement</h2><p>Upload each renewed document under the same document type. Earlier documents remain on record. A manager must approve you before new WOs can be assigned.</p><form className="tenant-form" onSubmit={upload}><label>Document type<select value={type} onChange={e=>setType(e.target.value)}>{[...new Set([...current.map(d=>d.document_type),type])].map(t=><option key={t}>{t}</option>)}</select></label><label>New expiry date<input required type="date" min={londonToday()} value={expiry} onChange={e=>setExpiry(e.target.value)}/></label><label>Replacement document<input required type="file" accept="application/pdf,image/jpeg,image/png,image/webp" onChange={e=>setFile(e.target.files?.[0]??null)}/></label><button className="primary" disabled={busy||!file}>{busy?'Uploading…':'Upload replacement'}</button></form>{message&&<p role="status">{message}</p>}</section></div></main>;
}
