import {createHash} from "node:crypto";
import {parse} from "csv-parse/sync";
import {NextRequest,NextResponse} from "next/server";
import {createClient} from "../../../../../lib/supabase/server";
import {bankDate,bankMoney,type BankMapping} from "../../../../../lib/bank-reconciliation";
async function access(raw:string){const blockId=Number(raw);if(!Number.isSafeInteger(blockId)||blockId<1)throw new Error("Invalid block.");const supabase=await createClient();const {data:{user}}=await supabase.auth.getUser();if(!user?.email)throw new Error("Sign in required.");const {data:member}=await supabase.from("portal_members").select("role").eq("email",user.email.toLowerCase()).maybeSingle();if(!["owner","admin","manager"].includes(member?.role??""))throw new Error("Manager access required.");const {data:block}=await supabase.from("blocks").select("id").eq("id",blockId).maybeSingle();if(!block)throw new Error("Block unavailable.");return {supabase,blockId};}
export async function GET(request:NextRequest,{params}:{params:Promise<{blockId:string}>}){try{const {supabase,blockId}=await access((await params).blockId);const status=request.nextUrl.searchParams.get("status")??"Pending";if(!["Pending","Posted","Ignored"].includes(status))throw new Error("Invalid status.");const {data,error,count}=await supabase.from("bank_statement_rows").select("id,block_id,transaction_date,amount_pence,bank_reference,description,transaction_id,source_file,status,unit_id,payment_entry_id,imported_at",{count:"exact"}).eq("block_id",blockId).eq("status",status).order("id",{ascending:status==="Pending"}).limit(1000);if(error)throw new Error("Could not load statement rows.");return NextResponse.json({rows:data,count});}catch(e){return NextResponse.json({error:e instanceof Error?e.message:"Unavailable."},{status:400});}}
export async function POST(request:NextRequest,{params}:{params:Promise<{blockId:string}>}){
 try{const {supabase,blockId}=await access((await params).blockId);
 if(request.headers.get("content-type")?.includes("application/json")){
  const text=await request.text();if(text.length>100000)throw new Error("Request too large.");const body=JSON.parse(text);
  if(body.action==="post"){if(!Array.isArray(body.assignments)||body.assignments.length<1||body.assignments.length>1000||body.assignments.some((a:{id:number;unit_id:number})=>!Number.isSafeInteger(a.id)||!Number.isSafeInteger(a.unit_id)))throw new Error("Select valid payments and units.");const {data,error}=await supabase.rpc("post_bank_payments",{p_block_id:blockId,p_assignments:body.assignments});if(error)throw new Error("Payments were not posted. Check they are pending and assigned to this block.");return NextResponse.json({posted:data});}
  if(body.action==="ignore"){if(!Array.isArray(body.ids)||body.ids.length<1||body.ids.length>1000||body.ids.some((id:number)=>!Number.isSafeInteger(id)))throw new Error("Select valid rows.");const {data,error}=await supabase.from("bank_statement_rows").update({status:"Ignored"}).eq("block_id",blockId).eq("status","Pending").in("id",body.ids).select("id");if(error)throw new Error("Could not ignore these rows.");return NextResponse.json({ignored:data?.length??0});}
  throw new Error("Invalid action.");
 }
 if(Number(request.headers.get("content-length"))>2100000)throw new Error("Statement must be under 2 MB.");const form=await request.formData();const file=form.get("file");if(!(file instanceof File)||!file.name.toLowerCase().endsWith(".csv")||file.size>2000000)throw new Error("Upload a CSV bank statement under 2 MB.");const records=parse(await file.text(),{bom:true,trim:true,skip_empty_lines:true,max_record_size:20000}) as string[][];const headers=records[0];if(!headers?.length||headers.length>60||new Set(headers).size!==headers.length)throw new Error("Provide a CSV with unique column headings.");if(records.length<2||records.length>1001)throw new Error("Provide 1 to 1000 statement transactions.");if(records.some(row=>row.length!==headers.length))throw new Error("Each CSV row must match its column headings.");
 if(form.get("action")==="inspect")return NextResponse.json({headers,sample:records.slice(1,4)});
 const mapping=JSON.parse(String(form.get("mapping"))) as BankMapping;
 if(!mapping||!["ISO","UK"].includes(mapping.dateFormat)||!headers.includes(mapping.date)||(!mapping.reference&&!mapping.description)||(!mapping.amount&&!mapping.credit))throw new Error("Choose the date, reference/description and money-in or signed amount columns.");
 for(const key of ["reference","description","amount","credit","debit","transactionId"] as const)if(mapping[key]&&!headers.includes(mapping[key]))throw new Error("A selected column is missing.");
 const occurrence=new Map<string,number>();let skipped=0;
 const rows=records.slice(1).flatMap((values,index)=>{try{const get=(column:string)=>column?values[headers.indexOf(column)]:"";const date=bankDate(get(mapping.date),mapping.dateFormat);let amount;if(mapping.amount)amount=bankMoney(get(mapping.amount));else{const credit=bankMoney(get(mapping.credit)),debit=bankMoney(get(mapping.debit));if(credit<0||debit<0||credit&&debit)throw new Error("Money-in and money-out columns must be positive, with only one populated.");amount=credit-debit;}if(amount<=0){skipped++;return [];}
 const bank_reference=get(mapping.reference),description=get(mapping.description),transaction_id=get(mapping.transactionId);if(bank_reference.length>500||description.length>1000||transaction_id.length>200)throw new Error("Transaction details are too long.");const canonical=(s:string)=>s.toUpperCase().replace(/\s+/g," ").trim();const identity=JSON.stringify([date,amount,canonical(bank_reference),canonical(description)]);const n=(occurrence.get(identity)??0)+1;occurrence.set(identity,n);const fingerprint=createHash("sha256").update(transaction_id?`id:${transaction_id}`:`row:${identity}:${n}`).digest("hex");return [{fingerprint,transaction_date:date,amount_pence:amount,bank_reference,description,transaction_id,source_file:file.name.slice(0,200)}];}catch(e){throw new Error(`Row ${index+2}: ${e instanceof Error?e.message:"Invalid transaction."}`);}});
 if(!rows.length)return NextResponse.json({added:0,duplicates:0,skipped});const {data,error}=await supabase.rpc("stage_bank_statement",{p_block_id:blockId,p_rows:rows});if(error)throw new Error("Statement was not imported. Please check the transaction details.");return NextResponse.json({...data,skipped});
 }catch(e){return NextResponse.json({error:e instanceof Error?e.message:"Could not process statement."},{status:400});}
}
