"use client";
import {useCallback,useEffect,useMemo,useState} from "react";
import {useRouter} from "next/navigation";
import type {Unit} from "./types";
import {matchBankReference,type BankRow,type BankMapping} from "../lib/bank-reconciliation";
import {money} from "../lib/service-charges";
const emptyMapping:BankMapping={date:"",reference:"",description:"",amount:"",credit:"",debit:"",transactionId:"",dateFormat:"UK"};
const columns:[keyof Omit<BankMapping,"dateFormat">,string][]=[["date","Transaction date"],["reference","Payment reference"],["description","Description"],["amount","Signed amount (+ received, − paid out)"],["credit","Money in / credit (if no signed amount)"],["debit","Money out / debit (if separate columns)"],["transactionId","Bank transaction ID (recommended)"]];
export default function BankReconciliation({blockId,units}:{blockId:number;units:Unit[]}){
 const router=useRouter();const [file,setFile]=useState<File|null>(null),[headers,setHeaders]=useState<string[]>([]),[sample,setSample]=useState<string[][]>([]),[mapping,setMapping]=useState<BankMapping>(emptyMapping),[rows,setRows]=useState<BankRow[]>([]),[count,setCount]=useState(0),[status,setStatus]=useState("Pending"),[chosen,setChosen]=useState<Record<number,number>>({}),[selected,setSelected]=useState<number[]>([]),[busy,setBusy]=useState(false),[loading,setLoading]=useState(false),[message,setMessage]=useState("");
 const matches=useMemo(()=>new Map(rows.map(row=>[row.id,matchBankReference(row,units)])),[rows,units]);
 const endpoint=`/api/blocks/${blockId}/bank-statements`;
 const load=useCallback(async(signal?:AbortSignal)=>{setLoading(true);try{const r=await fetch(`${endpoint}?status=${status}`,{signal});const result=await r.json();if(!r.ok)throw new Error(result.error);if(signal?.aborted)return;setRows(result.rows);setCount(result.count);setSelected([]);}catch(e){if(!signal?.aborted)setMessage(e instanceof Error?e.message:"Could not load statement.");}finally{if(!signal?.aborted)setLoading(false);}},[endpoint,status]);
 useEffect(()=>{const controller=new AbortController();void load(controller.signal);return ()=>controller.abort();},[load]);
 async function inspect(next:File|null){setFile(null);setHeaders([]);setSample([]);setMapping(emptyMapping);setMessage("");if(!next)return;setBusy(true);try{const form=new FormData();form.set("action","inspect");form.set("file",next);const r=await fetch(endpoint,{method:"POST",body:form});const result=await r.json();if(!r.ok)throw new Error(result.error);setFile(next);setHeaders(result.headers);setSample(result.sample);const find=(patterns:RegExp[])=>result.headers.find((h:string)=>patterns.some(p=>p.test(h)))??"";setMapping({...emptyMapping,date:find([/^date$/i,/transaction.*date/i]),reference:find([/^reference$/i,/payment.*ref/i]),description:find([/description/i,/details/i,/narrative/i]),amount:find([/^amount$/i,/signed.*amount/i]),credit:find([/money.?in/i,/credit/i,/paid.?in/i]),debit:find([/money.?out/i,/debit/i,/paid.?out/i]),transactionId:find([/transaction.?id/i])});}catch(e){setMessage(e instanceof Error?e.message:"Could not inspect file.");}finally{setBusy(false);}}
 async function upload(){if(!file)return;setBusy(true);setMessage("");try{const form=new FormData();form.set("file",file);form.set("mapping",JSON.stringify(mapping));const r=await fetch(endpoint,{method:"POST",body:form});const result=await r.json();if(!r.ok)throw new Error(result.error);setMessage(`${result.added} incoming payments added for review; ${result.duplicates} duplicates skipped; ${result.skipped} outgoing or zero-value transactions skipped. No balances changed.`);setFile(null);setHeaders([]);setSample([]);if(status==="Pending")await load();else setStatus("Pending");}catch(e){setMessage(e instanceof Error?e.message:"Could not import statement.");}finally{setBusy(false);}}
 function assignment(row:BankRow){return chosen[row.id]??matches.get(row.id)?.unitId??0;}
 async function process(action:"post"|"ignore"){setBusy(true);setMessage("");try{const assignments=rows.filter(r=>selected.includes(r.id)).map(r=>({id:r.id,unit_id:assignment(r)}));if(action==="post"&&assignments.some(a=>!a.unit_id))throw new Error("Choose a unit for every selected payment.");const r=await fetch(endpoint,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(action==="post"?{action,assignments}:{action,ids:selected})});const result=await r.json();if(!r.ok)throw new Error(result.error);setMessage(action==="post"?`${result.posted} payments posted to the selected unit accounts.`:`${result.ignored} payments marked as ignored.`);await load();router.refresh();}catch(e){setMessage(e instanceof Error?e.message:"Could not reconcile payments.");}finally{setBusy(false);}}
 return <section className="panel tenant-card bank-reconciliation charge-screen-only"><p className="eyebrow">BANK RECONCILIATION</p><h2>Upload this block’s bank statement</h2><p>Drop a CSV exported from your bank, or choose a file. Match incoming payments using each unit’s fixed payment reference, then review and confirm. Uploads are kept for review even before residents and references are added.</p><label className="bank-drop" onDragOver={e=>e.preventDefault()} onDrop={e=>{e.preventDefault();if(!busy)void inspect(e.dataTransfer.files[0]??null);}}>Drop bank CSV here<input disabled={busy} type="file" accept=".csv,text/csv" onChange={e=>void inspect(e.target.files?.[0]??null)}/></label>
 {headers.length>0&&<div className="tenant-form"><h3>Match your statement columns</h3><p>{file?.name} · Only upload transactions for this block. Check the date format and preview before importing.</p><div className="bank-mapping">{columns.map(([key,label])=><label key={key}>{label}<select value={mapping[key]} onChange={e=>setMapping({...mapping,[key]:e.target.value})}><option value="">Not used</option>{headers.map(h=><option key={h}>{h}</option>)}</select></label>)}<label>Date format<select value={mapping.dateFormat} onChange={e=>setMapping({...mapping,dateFormat:e.target.value as BankMapping["dateFormat"]})}><option value="UK">DD/MM/YYYY</option><option value="ISO">YYYY-MM-DD</option></select></label></div><div className="block-table-wrap"><table className="block-table"><caption>First three transactions from the file</caption><thead><tr>{headers.map(h=><th key={h}>{h}</th>)}</tr></thead><tbody>{sample.map((values,i)=><tr key={i}>{values.map((v,j)=><td key={j}>{v}</td>)}</tr>)}</tbody></table></div>{!mapping.transactionId&&<p>Without a bank transaction ID, duplicate checks use the date, amount, reference and description. Check the duplicate count carefully when two genuine payments have identical details.</p>}<button className="primary" disabled={busy||!mapping.date||(!mapping.reference&&!mapping.description)||(!mapping.amount&&!mapping.credit)} onClick={()=>void upload()}>Import for review</button></div>}
 <p role="status">{message}</p><div className="bank-review-head"><h3>Statement payments</h3><label>Status<select value={status} disabled={busy} onChange={e=>{setStatus(e.target.value);setChosen({});}}><option>Pending</option><option>Posted</option><option>Ignored</option></select></label></div><p>{count} {status.toLowerCase()} payments{count>1000?" · Showing the first 1,000; process these to see the remainder":""}.</p>{loading?<p>Loading payments…</p>:rows.length?<><div className="block-table-wrap"><table className="block-table bank-review-table"><thead><tr>{status==="Pending"&&<th>Select</th>}<th>Date</th><th>Reference / description</th><th>Money in</th><th>Unit account</th><th>Match</th></tr></thead><tbody>{rows.map(row=>{const match=matches.get(row.id)!;return <tr key={row.id}>{status==="Pending"&&<td><input type="checkbox" aria-label={`Select payment ${row.id}`} checked={selected.includes(row.id)} disabled={busy} onChange={e=>setSelected(previous=>e.target.checked?[...previous,row.id]:previous.filter(id=>id!==row.id))}/></td>}<td>{row.transaction_date}</td><td><strong>{row.bank_reference||"No separate reference"}</strong><small>{row.description}</small><small>{row.source_file}{row.transaction_id?` · ${row.transaction_id}`:""}</small></td><td>{money(row.amount_pence)}</td><td>{status==="Pending"?<select aria-label={`Unit for payment ${row.id}`} disabled={busy} value={assignment(row)} onChange={e=>setChosen({...chosen,[row.id]:Number(e.target.value)})}><option value={0}>Choose unit</option>{units.map(u=><option key={u.id} value={u.id}>{u.unitNumber} · {u.paymentReference||"Reference not added"}</option>)}</select>:units.find(u=>u.id===row.unit_id)?.unitNumber??"—"}</td><td>{status==="Pending"?(chosen[row.id]!==undefined?"Manual assignment — review":match.reason):row.status}</td></tr>;})}</tbody></table></div>{status==="Pending"&&<div className="bank-actions"><button className="unit-secondary" disabled={busy} onClick={()=>setSelected(rows.filter(r=>matches.get(r.id)?.unitId!==null&&chosen[r.id]===undefined).map(r=>r.id))}>Select reference matches</button><button className="primary" disabled={busy||selected.length===0} onClick={()=>void process("post")}>Confirm & post {selected.length} payments</button><button className="unit-secondary" disabled={busy||selected.length===0} onClick={()=>void process("ignore")}>Ignore selected</button></div>}</>:<p>No {status.toLowerCase()} statement payments for this block.</p>}<p className="tenant-help">Confirming adds a separate payment to each unit ledger. Uploading the same transactions again does not post them twice. PDFs and scanned statements need a CSV export for this uploader.</p></section>;
}
