"use client";
import {useMemo,useState} from "react";
import {useRouter} from "next/navigation";
import {createClient} from "../lib/supabase/browser";
import type {BuildingSafetyRecord} from "./types";

type Props={blockId:number|null;records:BuildingSafetyRecord[]};
function field(notes:string|undefined,label:string){const line=(notes??"").split("\n").find(x=>x.startsWith(label+":"));return line?.slice(label.length+1).trim()??""}
export default function HealthSafetyRiskRegister({blockId,records}:Props){
 const router=useRouter();const[busy,setBusy]=useState<number|null>(null);
 const risks=useMemo(()=>records.filter(r=>r.category==="Risk Register"),[records]);
 async function setRiskStatus(r:BuildingSafetyRecord,next:string){setBusy(r.id);const supabase=createClient();await supabase.from("building_safety_records").update({status:next}).eq("id",r.id);setBusy(null);router.refresh()}
 return <main style={{padding:"24px",background:"#fff",borderRadius:12}}><div style={{display:"flex",justifyContent:"space-between",gap:20,alignItems:"end",marginBottom:20}}><div><p className="eyebrow">RISK REGISTER</p><h2 style={{margin:"4px 0"}}>Building Risk Register</h2><p style={{margin:0}}>Issues identified during Health & Safety audits are automatically carried into this register for action and close-out.</p></div><div><b>{risks.filter(r=>r.status!=="Closed").length}</b> open risk{risks.filter(r=>r.status!=="Closed").length===1?"":"s"}</div></div>{!blockId?<p>Select a building.</p>:risks.length===0?<div style={{padding:24,border:"1px solid #e5e7eb",borderRadius:10}}>No audit risks have been raised for this building.</div>:<div style={{overflowX:"auto"}}><table style={{width:"100%",borderCollapse:"collapse"}}><thead><tr>{["Risk / issue","Source","Audit date","Risk rating","Action required","Responsible person","Target date","Status","Close-out"].map(x=><th key={x} style={{textAlign:"left",padding:10,borderBottom:"1px solid #ddd",whiteSpace:"nowrap"}}>{x}</th>)}</tr></thead><tbody>{risks.map(r=><tr key={r.id}><td style={{padding:10,borderBottom:"1px solid #eee",minWidth:180}}><b>{r.title}</b><div style={{fontSize:12,marginTop:4}}>{field(r.notes,"Issue")}</div></td><td style={{padding:10,borderBottom:"1px solid #eee"}}>{field(r.notes,"Source")}</td><td style={{padding:10,borderBottom:"1px solid #eee"}}>{field(r.notes,"Audit date")}</td><td style={{padding:10,borderBottom:"1px solid #eee"}}>{field(r.notes,"Risk rating")||"To assess"}</td><td style={{padding:10,borderBottom:"1px solid #eee",minWidth:180}}>{field(r.notes,"Action required")||field(r.notes,"Issue")}</td><td style={{padding:10,borderBottom:"1px solid #eee"}}>{field(r.notes,"Responsible person")||"To assign"}</td><td style={{padding:10,borderBottom:"1px solid #eee"}}>{r.dueDate||"—"}</td><td style={{padding:10,borderBottom:"1px solid #eee"}}><b>{r.status}</b></td><td style={{padding:10,borderBottom:"1px solid #eee"}}>{r.status==="Closed"?<button className="outline" disabled={busy===r.id} onClick={()=>void setRiskStatus(r,"Action required")}>Reopen</button>:<button className="primary" disabled={busy===r.id} onClick={()=>void setRiskStatus(r,"Closed")}>{busy===r.id?"Saving…":"Close risk"}</button>}</td></tr>)}</tbody></table></div>}</main>
}
