'use client';
import {useState} from 'react';
import {useRouter} from 'next/navigation';
import {createClient} from '../lib/supabase/browser';
import type {Resident} from './types';
export default function ResidentArchiveAction({resident}:{resident:Resident}){
 const router=useRouter();const [busy,setBusy]=useState(false),[message,setMessage]=useState(''),[history,setHistory]=useState<{kind:string;text:string;date:string}[]|null>(null);
 async function archive(){if(busy||!confirm(resident.archivedAt?`Restore ${resident.fullName}? This will restore their access to this unit.`:`Archive ${resident.fullName}? Their history and the unit account stay on record. Access to this unit and future communications will stop.`))return;setBusy(true);setMessage('');const {data,error}=await createClient().from('residents').update({archived_at:resident.archivedAt?null:new Date().toISOString()}).eq('id',resident.id).select('id');if(error||!data?.length)setMessage(error?.code==='23505'?'An active resident already uses this unit and email. Review that assignment before restoring.':'Resident could not be updated.');else router.refresh();setBusy(false);}
 async function loadHistory(){setBusy(true);const db=createClient();const [requests,messages,orders]=await Promise.all([db.from('tenant_requests').select('id,title,status,description,manager_reply,created_at').eq('resident_id',resident.id).order('created_at',{ascending:false}),db.from('resident_messages').select('subject,message,sent_at').eq('resident_id',resident.id).order('sent_at',{ascending:false}),db.from('work_orders').select('work_order_number,title,description,status,created_at').eq('resident_id',resident.id).order('created_at',{ascending:false})]);if(requests.error||messages.error||orders.error)setMessage('History could not be loaded.');else setHistory([...(requests.data??[]).map(r=>({kind:`Maintenance #${r.id} · ${r.status}`,text:`${r.title}\n${r.description}\n${r.manager_reply}`,date:r.created_at})),...(messages.data??[]).map(m=>({kind:m.subject,text:m.message,date:m.sent_at})),...(orders.data??[]).map(w=>({kind:`${w.work_order_number} · ${w.status}`,text:`${w.title}\n${w.description||''}`,date:w.created_at}))].sort((a,b)=>b.date.localeCompare(a.date)));setBusy(false);}
 return <div className="resident-archive-actions"><button className="outline" disabled={busy} onClick={()=>void archive()}>{resident.archivedAt?'Restore':'Archive'}</button>{resident.archivedAt&&<details onToggle={e=>{if(e.currentTarget.open&&history===null&&!busy)void loadHistory();}}><summary>Resident history</summary><p>Archived: {new Date(resident.archivedAt).toLocaleDateString('en-GB')}. The unit’s service charge history remains in Service charges.</p>{history?.length?history.map((h,i)=><article key={i}><strong>{h.kind}</strong><small>{new Date(h.date).toLocaleDateString('en-GB')}</small><p style={{whiteSpace:'pre-wrap'}}>{h.text}</p></article>):<p>{history===null?'Loading history…':'No maintenance requests, work orders or communications recorded.'}</p>}</details>}{message&&<p role="status">{message}</p>}</div>;
}
