"use client";
import {chargeSummary,money,type ChargeEntry} from "../lib/service-charges";
export type ChargeProperty={building:string;address:string;unit:string;company:string;resident?:string;financialYearEnd?:string};
const displayDate=(date:string)=>new Intl.DateTimeFormat("en-GB",{day:"numeric",month:"long",year:"numeric",timeZone:"UTC"}).format(new Date(`${date}T12:00:00Z`));
export default function ServiceChargeLedger({entries,today,property}:{entries:ChargeEntry[];today:string;property:ChargeProperty}){
 const s=chargeSummary(entries,today);
 const ordered=[...entries].sort((a,b)=>a.entry_date.localeCompare(b.entry_date)||a.id-b.id);
 let balance=0;
 const rows=ordered.map(e=>{const scheduled=e.entry_date>today;if(!scheduled)balance+=e.entry_type==="Charge"?e.amount_pence:-e.amount_pence;return {entry:e,scheduled,balance};});
 return <><section className="stat-grid charge-screen-only"><article className="stat"><div><span>{s.balance<0?"Credit balance":"Account balance"}</span><strong>{money(Math.abs(s.balance))}</strong></div></article><article className="stat"><div><span>Due now</span><strong>{money(s.due)}</strong></div></article><article className="stat"><div><span>Overdue</span><strong>{money(s.overdue)}</strong></div></article><article className="stat"><div><span>Payments recorded</span><strong>{money(s.payments)}</strong></div></article></section>
 <article className="charge-statement"><header className="charge-document-head"><div><p className="eyebrow">SERVICE CHARGES</p><h2>Account statement</h2><p>{property.company||"Management company not recorded"}</p></div><button className="unit-secondary charge-screen-only" onClick={()=>window.print()}>Print / Save PDF</button></header><p className="charge-date">{displayDate(today)}</p><address className="charge-recipient">{property.resident&&<strong>{property.resident}<br/></strong>}{property.unit}<br/>{property.building}<br/>{property.address||"Development address not recorded"}</address>
 <dl className="charge-property"><div><dt>Property</dt><dd>{property.unit} · {property.building}<span>{property.address||"Development address not recorded"}</span></dd></div>{property.financialYearEnd&&<div><dt>Financial year end</dt><dd>{property.financialYearEnd}</dd></div>}<div><dt>Statement date</dt><dd>{displayDate(today)}</dd></div></dl>
 <div className="block-table-wrap"><table className="charge-document-table"><caption>Charges, payments and credits for this home</caption><thead><tr><th>Date / Reference</th><th>Description</th><th>Debit £</th><th>Credit £</th><th>Balance £</th></tr></thead><tbody>{rows.map(({entry:e,scheduled,balance})=><tr key={e.id}><td>{displayDate(e.entry_date)}<small>{e.reference}</small></td><td>{e.description}<small>{e.entry_type}{scheduled?" · Scheduled":""}{e.due_date?` · Due ${displayDate(e.due_date)}`:""}</small></td><td>{e.entry_type==="Charge"?money(e.amount_pence):"—"}</td><td>{e.entry_type!=="Charge"?money(e.amount_pence):"—"}</td><td>{scheduled?"Scheduled":money(balance)}</td></tr>)}{!rows.length&&<tr><td colSpan={5}>No service charge records have been added for this home yet.</td></tr>}</tbody><tfoot><tr><th colSpan={2}>Posted totals</th><td>{money(s.totalCharges)}</td><td>{money(s.payments+s.credits)}</td><td>{money(s.balance)}</td></tr></tfoot></table></div>
 <div className="charge-total"><span>{s.balance<0?"Account in credit":"Outstanding balance"}</span><strong>{money(Math.abs(s.balance))}</strong></div><p className="charge-document-note">Payments and credits are applied to charges in due-date order. Scheduled entries are excluded from the posted totals and balance.</p><footer className="charge-payment-advice"><h3>Account details</h3><p><strong>Development:</strong> {property.building}<br/><span className="charge-address">{property.address||"Development address not recorded"}</span></p><p><strong>Unit:</strong> {property.unit}<br/><strong>Due now:</strong> {money(s.due)}</p><p>Use the reference on the relevant charge when contacting your managing agent. This account statement is not a payment demand.</p></footer></article></>;
}
