"use client";
import {useState} from "react";
import {useRouter} from "next/navigation";
import {createClient} from "../lib/supabase/browser";
export type WOSubmission={id:string;dispatch_id:number;job_card_path:string;invoice_path:string;job_card_name:string;invoice_name:string;uploaded_at:string;notification_status:string};
export default function WorkOrderWorkflow({workOrderId,dispatchId,submissions,manager,canSend}:{workOrderId:number;dispatchId?:number;submissions:WOSubmission[];manager:boolean;canSend:boolean}){
 const router=useRouter();const [jobCard,setJobCard]=useState<File|null>(null),[invoice,setInvoice]=useState<File|null>(null),[busy,setBusy]=useState(false),[message,setMessage]=useState("");
 async function invoke(body:Record<string,unknown>){const {data,error}=await createClient().functions.invoke("work-order-workflow",{body});if(error){let detail=error.message;try{const r=await error.context?.json();detail=r?.error??detail;}catch{}throw new Error(detail);}if(data?.error)throw new Error(data.error);return data;}
 async function send(){setBusy(true);setMessage("");try{const result=await invoke({event:"send",workOrderId});setMessage(result.alreadySent?"This work order has already been emailed to the contractor.":"Work order emailed to the contractor with the secure upload link.");router.refresh();}catch(e){setMessage(e instanceof Error?e.message:"Could not send work order.");}finally{setBusy(false);}}
 async function upload(e:React.FormEvent){e.preventDefault();if(!dispatchId||!jobCard||!invoice||busy)return;setBusy(true);setMessage("");const client=createClient(),id=crypto.randomUUID();const uploaded:string[]=[];let saved=false;try{const {data:{user}}=await client.auth.getUser();if(!user?.email)throw new Error("Sign in again.");const paths:string[]=[];for(const [kind,file] of [["job-card",jobCard],["invoice",invoice]] as const){const types:Record<string,string>={"application/pdf":"pdf","image/jpeg":"jpg","image/png":"png"};const extension=types[file.type];if(!extension||file.size>10485760||file.size===0)throw new Error("Upload a PDF, JPG or PNG up to 10 MB for each document.");const path=`${dispatchId}/${id}/${kind}.${extension}`;const {error}=await client.storage.from("work-order-documents").upload(path,file,{contentType:file.type,upsert:false});if(error)throw new Error("Could not upload "+kind+". Please try again.");uploaded.push(path);paths.push(path);}const {error}=await client.from("work_order_submissions").insert({id,dispatch_id:dispatchId,job_card_path:paths[0],invoice_path:paths[1],job_card_name:jobCard.name.slice(0,200),invoice_name:invoice.name.slice(0,200),uploaded_by:user.email.toLowerCase()});if(error)throw new Error("Documents could not be submitted.");saved=true;setJobCard(null);setInvoice(null);try{await invoke({event:"notify",submissionId:id});setMessage("Invoice and job card submitted. The property manager has been emailed.");}catch(e){setMessage("Documents submitted successfully. Manager email is pending: "+(e instanceof Error?e.message:"notification unavailable"));}router.refresh();}catch(e){if(!saved&&uploaded.length)await client.storage.from("work-order-documents").remove(uploaded);setMessage(e instanceof Error?e.message:"Upload failed.");}finally{setBusy(false);}}
 async function open(path:string){const {data,error}=await createClient().storage.from("work-order-documents").createSignedUrl(path,60);if(error||!data){setMessage("Document could not be opened.");return;}window.open(data.signedUrl,"_blank","noopener,noreferrer");}
 return <section className="panel tenant-card wo-workflow">{manager?<><h2>Contractor dispatch</h2><p>Send this work order to its assigned approved contractor. Their link requires sign-in using the contractor email address.</p><button className="primary" disabled={busy||!canSend} onClick={()=>void send()}>{busy?"Working…":"Send work order to contractor"}</button></>:<><h2>Submit the invoice and completed job card</h2><p>Both documents are required. Include the block name, expense account and WO number on the invoice.</p><form className="tenant-form" onSubmit={upload}><label>Completed job card<input required type="file" accept="application/pdf,image/jpeg,image/png" onChange={e=>setJobCard(e.target.files?.[0]??null)}/></label><label>Invoice<input required type="file" accept="application/pdf,image/jpeg,image/png" onChange={e=>setInvoice(e.target.files?.[0]??null)}/></label><button className="primary" disabled={busy||!jobCard||!invoice}>{busy?"Uploading…":"Submit invoice & job card"}</button></form></>}{message&&<p role="status">{message}</p>}<h3>Submitted documents</h3>{submissions.length?submissions.map(s=><article key={s.id} className="wo-submission"><p>{new Date(s.uploaded_at).toLocaleString("en-GB")} · Manager email: {s.notification_status}</p><button className="unit-secondary" onClick={()=>void open(s.job_card_path)}>Job card: {s.job_card_name}</button><button className="unit-secondary" onClick={()=>void open(s.invoice_path)}>Invoice: {s.invoice_name}</button>{manager&&s.notification_status!=="Sent"&&<button disabled={busy} className="unit-secondary" onClick={async()=>{setBusy(true);try{await invoke({event:"notify",submissionId:s.id});setMessage("Manager notification sent.");router.refresh();}catch(e){setMessage(e instanceof Error?e.message:"Notification failed.");}finally{setBusy(false);}}}>Retry manager notification</button>}</article>):<p>No invoice and job card have been submitted yet.</p>}</section>;
}
