"use client";
import type {ChargeDocumentSettings} from "../../lib/service-charge-document";
import ServiceChargeLedger from "../ServiceChargeLedger";
import {chargeSummary,money,type ChargeEntry} from "../../lib/service-charges";
import { useState } from "react";
import Link from "next/link";
import { useRouter } from "next/navigation";
import { createClient } from "../../lib/supabase/browser";
export type TenantHome={paymentReference:string|null;documentSettings?:ChargeDocumentSettings;residentId:number;unitId:number;blockId:number;name:string;email:string;phone:string|null;unit:string;building:string;address:string;company:string;manager:string};
export type TenantRequest={id:number;resident_id:number;block_id:number;unit_id:number;title:string;description:string;category:string;priority:string;status:string;manager_reply:string;created_at:string;updated_at:string};
export type ResidentCommunication={id:number;resident_id:number;block_id:number;subject:string;message:string;sent_at:string};
export default function TenantPortal({communications,communicationsUnavailable,charges,today,homes,requests,preview}:{communications:ResidentCommunication[];communicationsUnavailable:boolean;charges:ChargeEntry[];today:string;homes:TenantHome[];requests:TenantRequest[];preview:boolean}){
 const router=useRouter();
 const [homeId,setHomeId]=useState(homes[0].residentId),[view,setView]=useState<"home"|"report"|"requests"|"charges"|"communications">("home");
 const [title,setTitle]=useState(""),[description,setDescription]=useState(""),[category,setCategory]=useState("General"),[priority,setPriority]=useState("Normal"),[busy,setBusy]=useState(false),[message,setMessage]=useState("");
 const home=homes.find(h=>h.residentId===homeId)??homes[0];
 const myCommunications=communications.filter(c=>c.resident_id===home.residentId&&c.block_id===home.blockId);
 const mine=requests.filter(r=>r.resident_id===home.residentId);
 async function submit(e:React.FormEvent){
  e.preventDefault();if(preview||busy)return;setBusy(true);setMessage("");
  try{
   const {error}=await createClient().from("tenant_requests").insert({block_id:home.blockId,unit_id:home.unitId,resident_id:home.residentId,title:title.trim(),description:description.trim(),category,priority,created_by:home.email});
   if(error)throw error;
   setTitle("");setDescription("");setMessage("Your maintenance request has been sent to the managing team.");setView("requests");router.refresh();
  }catch{setMessage("Your request could not be sent. Please try again.");}finally{setBusy(false);}
 }
 return <main className="tenant-shell">
  <header className="tenant-header"><Link href="/tenant" className="tenant-brand">London Property Portal<span>Tenant portal</span></Link>{preview?<Link href="/">Back to management</Link>:<button onClick={async()=>{await createClient().auth.signOut();window.location.href="/tenant/login";}}>Sign out</button>}</header>
  {preview&&<div className="tenant-preview" role="status">Tenant preview · {home.name}. Requests cannot be submitted from this preview.</div>}
  <div className="tenant-content"><div className="tenant-heading"><p className="eyebrow">MY HOME</p><h1>{home.building}</h1><p>{home.unit} · {home.address.replace(/\n/g,", ")}</p>{homes.length>1&&<label>Choose home<select value={homeId} onChange={e=>{setHomeId(Number(e.target.value));setMessage("");}}>{homes.map(h=><option key={h.residentId} value={h.residentId}>{h.unit} · {h.building}</option>)}</select></label>}</div>
  <nav className="tenant-tabs" aria-label="Tenant portal">{([["home","My home"],["report","Report an issue"],["requests","My requests"],["charges","Service charges"],["communications","Communications"]] as const).map(([key,label])=><button key={key} aria-current={view===key?"page":undefined} className={view===key?"active":""} onClick={()=>{setView(key);setMessage("");}}>{label}</button>)}</nav>
  {message&&<p className="unit-message" role="status">{message}</p>}
  {view==="home"&&<div className="tenant-grid"><section className="panel tenant-card"><p className="eyebrow">WELCOME, {home.name.toUpperCase()}</p><h2>Your home details</h2><dl><div><dt>Home</dt><dd>{home.unit}</dd></div><div><dt>Building</dt><dd>{home.building}</dd></div><div><dt>Managing agent</dt><dd>{home.company||"Not recorded"}</dd></div><div><dt>Property manager</dt><dd>{home.manager||"Not recorded"}</dd></div><div><dt>Email</dt><dd>{home.email}</dd></div><div><dt>Phone</dt><dd>{home.phone||"Not recorded"}</dd></div></dl></section><section className="panel tenant-card"><p className="eyebrow">MAINTENANCE</p><h2>{mine.filter(r=>r.status!=="Complete").length} open requests</h2><p>Report a maintenance issue and follow the managing team’s updates.</p><button className="primary" onClick={()=>setView("report")}>Report an issue</button><button className="unit-secondary" onClick={()=>setView("requests")}>View my requests</button></section></div>}
  {view==="home"&&<section className="panel tenant-card"><h2>Service charges</h2><p>{charges.some(c=>c.unit_id===home.unitId)?`Account balance: ${money(chargeSummary(charges.filter(c=>c.unit_id===home.unitId),today).balance)}`:"No charges have been added for your home yet."}</p><button className="unit-secondary" onClick={()=>setView("charges")}>View my account</button></section>}
  {(view==="home"||view==="communications")&&<section className="panel tenant-card tenant-communications"><div className="panel-head"><div><p className="eyebrow">MANAGING TEAM</p><h2>{view==="home"?"Latest communications":"Resident communications"}</h2></div>{view==="home"&&myCommunications.length>3&&<button className="unit-secondary" onClick={()=>setView("communications")}>View all messages</button>}</div>{communicationsUnavailable?<p role="status">Communications could not be loaded. Please refresh to try again.</p>:myCommunications.length?<div className="tenant-message-list">{(view==="home"?myCommunications.slice(0,3):myCommunications).map(c=><article key={c.id}><div><h3>{c.subject}</h3><time dateTime={c.sent_at}>{new Intl.DateTimeFormat("en-GB",{dateStyle:"medium",timeStyle:"short",timeZone:"Europe/London"}).format(new Date(c.sent_at))}</time></div>{view==="home"?<><p className="tenant-message-excerpt">{c.message.length>240?c.message.slice(0,240)+"…":c.message}</p><details><summary>Read full message</summary><p className="tenant-message-body">{c.message}</p></details></>:<p className="tenant-message-body">{c.message}</p>}</article>)}</div>:<p>No communications have been sent to you for this home yet.</p>}{view==="communications"&&myCommunications.length>=200&&<p>Showing recent messages.</p>}</section>}
  {view==="charges"&&<ServiceChargeLedger entries={charges.filter(c=>c.unit_id===home.unitId)} today={today} property={{paymentReference:home.paymentReference,settings:home.documentSettings,building:home.building,address:home.address,unit:home.unit,company:home.company,resident:home.name}}/>}
  {view==="report"&&<section className="panel tenant-card tenant-form"><h2>Report a maintenance issue</h2><p>{home.unit} · {home.building}</p><form onSubmit={submit}><label>Issue title<input required maxLength={200} value={title} onChange={e=>setTitle(e.target.value)} placeholder="For example: leaking kitchen tap"/></label><div className="tenant-grid"><label>Category<select value={category} onChange={e=>setCategory(e.target.value)}>{["General","Plumbing","Electrical","Heating","Cleaning","Security","Other"].map(v=><option key={v}>{v}</option>)}</select></label><label>Priority<select value={priority} onChange={e=>setPriority(e.target.value)}>{["Low","Normal","High","Urgent"].map(v=><option key={v}>{v}</option>)}</select></label></div><label>What is happening?<textarea required maxLength={5000} rows={5} value={description} onChange={e=>setDescription(e.target.value)} placeholder="Describe the issue, its location and when it started."/></label><p className="tenant-help">For immediate danger, call the emergency services. This form is not monitored as an emergency service.</p><button className="primary" disabled={preview||busy||!title.trim()||!description.trim()}>{busy?"Sending…":"Submit request"}</button></form></section>}
  {view==="requests"&&<section className="panel tenant-card"><div className="panel-head"><h2>My maintenance requests</h2><button className="unit-secondary" onClick={()=>setView("report")}>Report an issue</button></div>{mine.length?<div className="tenant-request-list">{mine.map(r=><article key={r.id}><div className="tenant-request-heading"><h3>#{r.id} · {r.title}</h3><span>{r.status}</span></div><p>{r.description}</p><small>{r.category} · {r.priority} · Reported {new Intl.DateTimeFormat("en-GB",{dateStyle:"medium",timeZone:"Europe/London"}).format(new Date(r.created_at))}</small>{r.manager_reply&&<div className="tenant-reply"><strong>Managing team update</strong><p>{r.manager_reply}</p></div>}</article>)}</div>:<p>You have not reported any maintenance issues yet.</p>}</section>}
  </div>
 </main>;
}
